name: "Build CI"

on: [push, pull_request]
 

jobs:
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build application
        run: docker-compose up -d

  test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install react
          working-directory: ./library_front
          run: npm install 
        - name: Run test
          working-directory: ./library_front
          run: npm run test
